#!/usr/bin/env node

var fs = require('fs');
var Module = require('module');
var path = require('path');
var repl = require('repl');
var util = require('util');
var vm = require('vm');

//var removeTypes = require('./index');
//require('./register');

var usage = 'Usage: webpack-node [options] [ script.js ] [arguments] \n' +

'\nOptions:\n' +
'  -h, --help            Show this message\n' +
'  -v, --version         Prints the current version of flow-node\n' +
'  -e, --eval script     Evaluate script\n' +
'  -p, --print script    Evaluate script and print result\n' +
'  -c, --check           Syntax check script without executing\n';

// Collect arguments
var evalScript;
var printScript;
var checkSource;
var source;
var i = 2;
while (i < process.argv.length) {
  var arg = process.argv[i++];
  if (arg === '-h' || arg === '--help') {
    process.stdout.write(usage);
    process.exit(0);
  } else if (arg === '-v' || arg === '--version') {
    process.stdout.write('v' + require('./package').version);
    process.exit(0);
  } else if (arg === '-e' || arg === '--eval') {
    evalScript = process.argv[i++];
    if (!evalScript) {
      process.stderr.write('flow-node: ' + arg + ' requires an argument');
      return process.exit(1);
    }
  } else if (arg === '-p' || arg === '--print') {
    printScript = process.argv[i++];
    if (!printScript) {
      process.stderr.write('flow-node: ' + arg + ' requires an argument');
      return process.exit(1);
    }
  } else if (arg === '-c' || arg === '--check') {
    checkSource = true;
  } else if (arg[0] !== '-') {
    source = arg;
    break;
  }
}

// Evaluate and possibly also print a script.
if (evalScript || printScript) {
  global.__filename = '[eval]';
  global.__dirname = process.cwd();
  var evalModule = new Module(global.__filename);
  evalModule.filename = global.__filename;
  evalModule.paths = Module._nodeModulePaths(global.__dirname);
  global.exports = evalModule.exports;
  global.module = evalModule;
  global.require = evalModule.require.bind(evalModule);
  var result = vm.runInThisContext(
    removeTypes(evalScript || printScript, { checkPragma: false }),
    { filename: global.__filename }
  );

  if (printScript) {
    process.stdout.write((typeof result === 'string' ? result : util.inspect(result)) + '\n');
  }

// Or check the source for syntax errors but do not run it.
} else if (source && checkSource) {
  var code = fs.readFileSync(source, 'utf8');
  try {
    removeTypes(code);
  } catch (error) {
    var lines = code.split(/\r\n?|\n|\u2028|\u2029/);
    process.stdout.write(source + ':' + error.loc.line + '\n');
    process.stdout.write(lines[error.loc.line - 1] + '\n');
    process.stdout.write(Array(error.loc.column + 1).join(' ') + '^\n');
    process.stdout.write(error.stack + '\n');
    return process.exit(1);
  }

// Or run the script.
} else if (source) {
  var absoluteSource = path.resolve(process.cwd(), source);
  process.argv = [ 'node' ].concat(
    process.argv.slice(2, i - 1),
    absoluteSource,
    process.argv.slice(i)
  );
  process.execArgv.unshift(__filename);
  Module.runMain();

// Or begin a REPL.
} else {
	var context = process.cwd();
  var webpack = require('webpack');
  var ModuleDependency = require('webpack/lib/dependencies/PrefetchDependency');
  var codeLoader = require.resolve('./code-loader');
  var compiler = webpack({
    plugins: [],
    target: 'node',
    module: {
      loaders: [
        {test: /\.md/, loader: 'file'},
        {test: /\.css/, loader: 'css?modules'}
      ]
    }
  });
	var params = compiler.newCompilationParams();
	compiler.applyPlugins("compile", params);
	var compilation = compiler.newCompilation(params);
  compilation.dependencyFactories.set(
    ModuleDependency,
    params.normalModuleFactory
  );
  repl.start({
    prompt: '> ',
    input: process.stdin,
    output: process.stdout,
    useGlobal: true,
    eval: function (code, context, filename, callback) {
      code = code.replace(/\!/g, '###');
      var error;
      var result;
      var dep = new ModuleDependency('!!' + codeLoader + '?' + code + '!');
      compilation.prefetch(process.cwd(), dep, function(err, mod) {
        if (err) {
          return callback(err);
        }
        console.log(mod)
        try {
          result = evalModule(mod, context);
        } catch (runError) {
          error = runError;
        }
        callback(error, result);
      });
    }
  });
}

function evalModule(mod, context, asModule) {
  if (!vm.isContext(context)) {
    context = vm.createContext(context);
  }
  context.__webpack_public_path__ = '/';
  let source = `(function(exports, require, module, __filename, __dirname){ ${asModule ? '' : 'return '} ${mod._source.source()} });`;
  let __filename = mod.resource;
  let __dirname = mod.context;
  let module = {exports: {}};
  let require = makeRequireFor(mod);
  let wrapper = vm.runInContext(source, context, {filename: mod.resource});
  let result = wrapper(module.exports, require, module, __filename, __dirname);
  if (asModule) {
    return module.exports;
  } else {
    return result;
  }
}

function makeRequireFor(module) {
  function require(request) {
    for (let i = 0; i < module.dependencies.length; i++) {
      if (module.dependencies[i].request === request) {
        return evalModule(module.dependencies[i].module, {}, true);
      }
    }
    throw new Error('unable to resolve: ' + request);
  }

  return require;
}
